### ISSUE TITLE
The planning/demo page contains a factual inaccuracy.

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-sysadmin-guide#182]
On the [planning/demo](https://docs.civicrm.org/sysadmin/en/latest/planning/demo) page it is stated that:

> "CiviCRM hosts several demo sites - there is at least one for each of the supported **Content Management Systems** (CMS) - Drupal, Joomla, and WordPress. The demo sites present a working copy of the latest stable version of CiviCRM with sample data. You can use them to play around with CiviCRM, but be aware that they are publicly viewable so you shouldn't enter personal data."

So the following issues arise:

1. There is no demo for Backdrop which is one of the supported CMS'
1. The demo sites aren't always running on the latest stable - we should be clearer that these are "best effort" sandboxes and not all of these are easy to automate.

**Comment by totten** [comment]
D7 and WP are in the best shape.

For Backdrop, there is a site https://bmaster.demo.civicrm.org/ - but the `demo` user [needs to be setup](https://lab.civicrm.org/infra/ops/issues/906).

Agree those sites aren't running `stable` - they're running `master`. As we discussed in some other issue, this should probably be updated so that both `master` and stable are available. But for the moment, it'd be accurate to just say `master`.

Joomla is the outlier that doesn't follow this pattern. D8 is coming soon.

**Comment by MikeyMJCO** [comment]
Fixed
