### ISSUE TITLE
Where do SMS setup docs belong?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#6]
We currently have this page on [setting up SMS delivery](https://docs.civicrm.org/user/en/latest/sms-text-messaging/set-up/) in the User Guide. I'm moving a handful of pages from the User Guide over to the Sysadmin Guide and curious if this one should come over. It feels like a bit of a grey area. On one hand it's very similar to the [email system configuration](https://docs.civicrm.org/user/en/latest/advanced-configuration/email-system-configuration/) page which I think definitely should get moved to the Sysadmin Guide. On the other hand it's quite a bit simpler. 

Would anyone care to weigh in with an opinion? I'm leaning towards moving it to the Sysadmin Guide.

**Comment by MegaphoneJon** [comment]
+1 for sysadmin guide.

**Comment by michaelmcandrew** [comment]
It involves installing an extension, signing up for an account with an sms
provider, both of which I would classify as admin tasks, not *system*
administrator tasks / I don't think you need to be a system administrator
to do them. Hence I would go for the user and admin guide.

**Comment by seamuslee001** [comment]
I see Michael McAndrew's point here but i would also think that the whole "installing an exension" thing is a bit boarderline. I know for instance there will be people who would probably be confident enough in doing some of the setup of CiviCRM i work with who have 0 clue how to install extensions etc or know what the heck they are and then people doing similar work who would be like yep i get this extensions business i know how to install all this i'm good with this. For me i would be a +1 on the sysadmin guide especially if all the other main high end of administration e.g. installation / upgrade is in here. Also i feel like especially with CallHub coming onto the scene it maybe necessary to refactor the SMS content to be more generic rather than referencing twilio and clickatel specifically but then perhaps have separate pages on setting up twilio setting up callhub setting up clickatel etc

**Comment by nganivet** [comment]
+1 on sysadmin guide since the extensions requires signing-up to an external service, knowing about API keys, potentially debugging if it does not work, etc.

However we should have in the user guide a placeholder text that links to the sysadmin guide for installing / configuring SMS sending.

**Comment by michaelmcandrew** [comment]
Hey there, here is some broader context behind my thinking.

When we sat down to write the user guide, one of our key aims was to impart knowledge that helped non profits work on their CiviCRM without having to go to expensive consultants - indeed that is a key aim of CiviCRM itself - help mere mortals to to do stuff that previously they would have had to go to experts for.

That said, there are some tasks that it makes sense for an expert to do, like installation, hosting, upgrades, etc. In deciding what to put in and what to leave out of the user guide, our guiding principle was: *Everything that you can do via the GUI should go in the user guide*.

In the case of integrating Twilio, you have to go to an external GUI, but that GUI is as easy to use as CiviCRM's. The tasks involved in setting up SMS (fill in a couple of simple forms and type in an API key) are as easy as many other admin tasks in CiviCRM's GUI. It is an *administrator* tasks for sure, but not a *system administrator* task.

A rough equivalent to the CMS world would be [adding a facebook feed to a wordpress site](https://en.support.wordpress.com/facebook-integration/). Yeah, it gets a bit technical, but it's not something you need to get onto the command line and get all `sudo` about.

Going further, installing those extensions that are available via the GUI is not a system administrator task either. Indeed the people that made the extensions GUI put a lot of effort explicitly into making it not a system administrator task (aside: yes, installing extensions that are not available via the GUI is a system administrator task, and the [user documentation could be improved to include this](https://github.com/civicrm/civicrm-user-guide/issues/199).


The user guide is really 'the user and administrator guide' with a more accessible name. Most readers for the user guide are admins / power users and the user guide covers lots of complex topics (like custom data, setting up price sets, membership types). It would be tempting to say are system administrator tasks, but I don't think that is helpful. I think it is alienating and against our mission to try and make this stuff accessible.  Putting SMS in the sys admin guide tells people you need to be a system administrator to configure SMS, which isn't true!

If we can try and keep the system admin guide to stuff that you need to be a system admin to do (and it is a fuzzy line, I know) then I think that would be much better.

End of rant - I won't weigh in any more :)

**Comment by seamuslee001** [comment]
I think its really touch n go and agree that its kinda in both camps in some respects.

I am now having read Michael's post thinking the content should be in the user guide but certainly perhaps at the key points e.g. installing extension. Maybe make a point of saying "If you have issues or are concerned please contact your system administrator to do help with this part" 

I would also imagine that there are also system configurations (like our system AFAIK) that would prevent the web user (www-data generally) writing to the extensions dir (security etc) so that takes out the use the GUI to download n install option as well. 

I certainly agree with the guiding principles outlined by Michael for the User Doc and i think perhaps a guiding principle for the sysadmins docs is that its about things that require CLI or server knowledge.

**Comment by michaelmcandrew** [comment]
> perhaps at the key points e.g. installing extension. Maybe make a point of saying "If you have issues or are concerned please contact your system administrator to do help with this part"

Yeah - that is a good point. We have done that to some extent in the user guide, e.g. in the [installation section of the extensions chapter](https://docs.civicrm.org/user/en/latest/introduction/extensions/#installing-extensions):

> If you do not see a list of extensions here, it may be that your system is not properly configured to manage extensions. You should consult your system administrator if this is the case.

I think that covers the intended use case but also orgs like yours, Seamus, where the sys admin / hosting company has it set up differently, since the user can then talk it over with the sys admin.

I agree that linkages between the two guides are important. At the beginning of the user guide we say:

> Some aspects of CiviCRM (such as installation, or custom development) are technical and outside the scope of this book. Although they are not covered here, we do point to other relevant sources of technical document which should be useful for people (like your service provider, or technical staff) who understand them.

In the useful skills section of the developer guide it says:

> Before diving into CiviCRM development, it's worth mentioning that a solid understanding of CiviCRM from the user's perspective can really help. You pick up the standard user interface patterns that you can re-use in your work, and you might even realise that the UI already provides the functionality you wish to develop. To that end, please see the User Guide.

And I'm guessing that Sean is planning something similar for the sys admin guide.

I suspect there are quite a few places where we could/should link better in the user guide and I'd be happy to help out with any linkages from the user side.

**Comment by seanmadsen** [comment]
I'm fine either way on this one. I think no matter how we try to draw a line between the User Guide and the System Administrator Guide, it will always be blurry. So the most important thing is we use links to bridge that blurry boundary and make related content discoverable. 

Michael's opinion seems quite strong and well articulated. This strength, combined with his docs experience, make me inclined to place a bit more weight in his position. But I'll give this thread a little more time to see if a consensus becomes clearer.

**Comment by joannechester** [comment]
I am strongly in favour of keeping the SMS setup in the User guide.  I think the guiding principle of _Everything that you can do via the GUI should go in the user guide._ that Michael outlined is spot on.
