### ISSUE TITLE
What i18n docs belong in the Sysadmin Guide?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#7]
The [D7 install page](https://docs.civicrm.org/sysadmin/en/latest/install/drupal7/#i18n) says:

> If using CiviCRM in another language than English, see the [internationalisation and localisation](https://wiki.civicrm.org/confluence/pages/viewpage.action?pageId=88408149) page about how to install files for running CiviCRM in other languages.

Do we want some of those i18n docs to go *in* the Sysadmin Guide? For example, if I follow a rabbit hole of links, I end up at this page on [Using CiviCRM in your own language](https://wiki.civicrm.org/confluence/display/CRMDOC/i18n+Administrator%27s+Guide%3A+Using+CiviCRM+in+your+own+language). That page is not currently part of my [migration](https://docs.google.com/spreadsheets/d/1kAuXQs6DatSj9Cr6q6DYquuEUNivK9_DvIztVZ_4_3c/edit#gid=0). Should it be? Should others be?

@bgm @nganivet thoughts?

**Comment by seanmadsen** [comment]
Note: my migration is heavily automated now, so as long as you can help me figure out where to put it, it'll be easy :slightly_smiling_face:

**Comment by mlutfy** [comment]
Ideally, I think it should be part of the sysadmin guide:

* downloading the civicrm-l10n.tar.gz file
* updating translation files
* enabling native gettext

From a sysadmin point of view, once the above 3 steps are done, the rest is part of the administration of CiviCRM (localization of date/money formats, enabling multi-lingual if necessary, etc). Also, the above 3 steps only apply to people who are self-hosting (I assume the sysadmin guide is oriented to people who self-host, whereas the Admin guide targets anyone who manages a CiviCRM instance)

If you create a placeholder for this in the structure, I will be happy to send a PR. A lot of that wiki doc is really old and we should aim to deprecate most of it. CiviCRM can now set locale-related settings during the installation, so we should focus on providing those defaults, instead of obscure steps to manually change those settings.

Example of deprecated docs that might be pushed in the gitlab wiki:

* "Updating your translation files manually using Transifex"
* "Localization cheat sheets"

I'm unsure about:

* "Inherit CMS language" and regional translations (ex: fr_CA)" ? -> since this requires changing a setting in `civicrm.settings.php`.. but it only applies if using multiple languages, and therefore something that administrators do only after the installation. (and which applies to both self-hosting and managed-hosting)

**Comment by seanmadsen** [comment]
Thanks @mlutfy 

Since this ticket was mostly just a question, I created #56 to track ongoing work and keep this discussion simplified from this point forward.
