### ISSUE TITLE
"Migrating Server" page gives conflicting advice, leads to errors

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/civicrm-sysadmin-guide#85]
See [here](https://civicrm.stackexchange.com/questions/24440/issues-with-migration-cannot-add-foreign-key-constraint/24443#24443) for reference.

In short: The migration guide tells you to install a fresh copy of Civi on the new server, then dump a copy of your old DB while selecting the "Add DROP TABLE / VIEW / PROCEDURE / FUNCTION / EVENT statement" option (in PHPMyAdmin).

This won't work because you'll be dropping tables that have foreign key constraints.  That line should be removed from the guide entirely.  Optionally, we can tell people to `DROP`/`CREATE` the entire Civi db.

**Comment by John-B** [comment]
The whole section on using phpmyadmin is a complete guide to moving an installation which largely overlaps with the other 'non-composer' version in the same page.

The logic of the phpmyadmin import, using a dump *sans* cache tables, and overwriting a freshly installed CiviCRM database, is problematic, and just removing the "Add DROP TABLE / VIEW / PROCEDURE / FUNCTION / EVENT statement"  will not fix it--it could be fixed by keeping the old cache tables in the dump, in which case the fresh CiviCRM install on the target seems pointless. 

For these reasons in my PR I have removed the entire phpMyAdmin section of the file, and added a short note pointing out the phpMyAdmin can be used for a simple db export, and import into an empty db.

**Comment by MikeyMJCO** [comment]
Resolved with #123
